/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MicrocmsCreate {
        "feed": string;
    }
    interface MicrocmsList {
        "feed"?: string;
    }
}
declare global {
    interface HTMLMicrocmsCreateElement extends Components.MicrocmsCreate, HTMLStencilElement {
    }
    var HTMLMicrocmsCreateElement: {
        prototype: HTMLMicrocmsCreateElement;
        new (): HTMLMicrocmsCreateElement;
    };
    interface HTMLMicrocmsListElement extends Components.MicrocmsList, HTMLStencilElement {
    }
    var HTMLMicrocmsListElement: {
        prototype: HTMLMicrocmsListElement;
        new (): HTMLMicrocmsListElement;
    };
    interface HTMLElementTagNameMap {
        "microcms-create": HTMLMicrocmsCreateElement;
        "microcms-list": HTMLMicrocmsListElement;
    }
}
declare namespace LocalJSX {
    interface MicrocmsCreate {
        "feed"?: string;
    }
    interface MicrocmsList {
        "feed"?: string;
    }
    interface IntrinsicElements {
        "microcms-create": MicrocmsCreate;
        "microcms-list": MicrocmsList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "microcms-create": LocalJSX.MicrocmsCreate & JSXBase.HTMLAttributes<HTMLMicrocmsCreateElement>;
            "microcms-list": LocalJSX.MicrocmsList & JSXBase.HTMLAttributes<HTMLMicrocmsListElement>;
        }
    }
}
