compatibility_date = "2022-11-25"
name = "worker-template"
workers_dev = true
routes = []
vars = { }
main = "./dist/_worker.js"
kv_namespaces = [{binding = "messageStore", id = "miniflareId", preview_id = "miniflareIdPreview"}]

[build]
command = "npm install && npm run build"

[build.upload]
format = "modules"
main = "./_worker.js"

[env.production]
workers_dev = false
vars = {  }
kv_namespaces = []

[env.local]
workers_dev = true
vars = { adminSecret = "adminSecret" }
kv_namespaces = [{binding = "messageStore", id = "miniflareId", preview_id = "miniflareIdPreview"}]
r2_buckets = []

[miniflare]
durable_objects_persist = "./.miniflare/durable-objects/"
kv_persist = "./.miniflare/kv/"
port = 8788
